payu-org/payu

payu/models/__init__.py
payu/models/mom6.py

The input scheme for MOM6 is pretty much exactly the same as GOLD, however the `MOM_input` file format is very slightly different to `GOLD_input` (this doesn't matter at the moment, as there's no dynamic configuration done by payu here).

Add a simple MOM6 model based on GOLD

---

payu/models/fms.py

Added config option to specify collate flags for fms

fms collate flags

---

payu/experiment.py
payu/subcommands/archive_cmd.py

Expose archive on cli. Add archive option to config.yaml

---

payu/experiment.py
payu/subcommands/setup_cmd.py

Added archive directory creation to setup (still also in archive), so that
`payu setup`
will create all the directories required for running.

Exposed setup to cli. 

---

payu/models/access.py
payu/models/fms.py
payu/models/model.py
payu/models/oasis.py

This includes those shutil.copy2 changes. Not sure if you wanted those or not.

Collatefix

---

payu/models/access.py
payu/models/oasis.py

 Issue 59: Changed the shutil.move() to shutil.copy2(), which will follow symlinks.

---

payu/cli.py

Fixes issue https://github.com/marshallward/payu/issues/64

Fixed issue with modpath manipulation stripping too much from path

---

payu/experiment.py
payu/models/__init__.py
payu/models/qgcm.py
payu/subcommands/run_cmd.py

Nasty hack to get it to work, need to explicitly specify the number of CPUs to be the same as the number of threads, and turn off binding
```yams
ncpureq: 4
mpthreads: 4
mpirun:
- --bind-to none
```

qgcm support

---

.travis.yml
payu/cli.py
payu/experiment.py
payu/fsops.py
payu/models/fms.py
payu/subcommands/collate_cmd.py
payu/subcommands/run_cmd.py
test/test_payu.py

- Add support for mppnccombine-fast
- Move collate options to dict
Addresses https://github.com/marshallward/payu/issues/121 and https://github.com/marshallward/payu/issues/122

Add support for fast collation with FMS models (mppnccombine-fast)

---

payu/models/fms.py

Adds an option to collate restarts. Requires new collate config layout, and adds:
```yaml
collate:
restart: true
```
option.
This addresses https://github.com/marshallward/payu/issues/124
Currently this collates restarts at the same time as collating outputs. This could be problematic if a new run starts before collation is finished. Also it might impact performance if restarts are collated before a new run can start, so single monolithic restart files are read in, rather than multiple tiled restarts.
It might be better to collate restarts when the restart clean-up procedure is invoked?
In any case, as an example, using `mppnccombine-fast` the outputs and restarts from a quarter degree run were collated in 3 minutes, using 2 x 4-cpu threads. In which case the above concern might be moot …

Add option to collate restart files as well as output files

---

payu/fsops.py

Fixes https://github.com/marshallward/payu/issues/142

Fix error supporting old collate options when collate: True not specified explicitly

---

payu/models/fms.py

This adds support for using a glob to specify the input files for collation as a result of a limitation on the number of command line arguments when `fork`ing in MPI as detailed in https://github.com/coecms/mppnccombine-fast/issues/24
The glob string is inferred from the base path. If it produces the same file list it replaces the file list. This should happen for most cases, but there ignore option means a glob may match too many files. 
The limit is probably MPI dependent, and I couldn't figure out a way to determine it, so just hardwired a number and issue a warning to the user if they are using `mppnccombine-fast`, have `glob` turned off and exceed this number.
Also had to call `envmod` and then call `lib_update` to make sure an MPI module is loaded, otherwise `mpirun` could not be …

Add support for globbing with mppnccombine-fast

---

payu/experiment.py

I knew there was something I had forgotten. Added control path to the job info dump.

Added control path to job yaml dump

---

payu/calendar.py
payu/cli.py
payu/experiment.py
payu/laboratory.py
payu/manifest.py
payu/models/access.py
payu/models/cice.py
payu/models/cice5.py
payu/models/fms.py
payu/models/model.py
payu/models/oasis.py
payu/models/um.py
payu/scheduler/pbs.py
payu/subcommands/args.py
payu/subcommands/run_cmd.py

Updates to payu to support ACCESS-ESM with manifests (and all the attendant changes).
This required linking inputs at the time they are added to the manifest, as the oasis driver prolifically links to other model work directories at setup. Probably a change that would have been made in any case.

ACCESS-ESM

---

payu/models/model.py

Hi!
Running into that `Exception` would raise a `KeyError` 👍

Fix string format in model.py

---

payu/fsops.py

fix depreciation warning for yaml.load. See https://github.com/payu-org/payu/issues/175

replace default yaml loader with safe option

---

payu/models/mitgcm.py

Attempt to fix https://github.com/payu-org/payu/issues/183
Support changes in model timestep by redefining the number of iterations for the model, and setting pickupsuff  so the old pickups are read in correctly.
Don't merge this yet. Am still testing.

Fix for MITgcm calendar issues

---

payu/fsops.py
payu/manifest.py
payu/models/cice.py
payu/models/cice5.py
payu/models/model.py
payu/models/mom.py
payu/models/oasis.py
payu/profilers/darshan.py
payu/profilers/oss.py
payu/subcommands/collate_cmd.py
payu/subcommands/ghsetup_cmd.py
payu/subcommands/profile_cmd.py
payu/subcommands/push_cmd.py
payu/subcommands/run_cmd.py
test/test_payu.py

Hi,
A few unused imports. Hopefully Travis-CI should be able to confirm they are not used.

Remove unused imports

---

.circleci/config.yaml
conda/meta.yaml

Add configuration for conda builds.
Add configuration for automated conda builds with CircleCI (on coecms channel)
Opening a new PR to try and get CircleCI to see it

Add automatic conda builds with CircleCI

---

conda/meta.yaml

Will also redo incorrect tagging if this passes.

Added payu list call to conda test to ensure code imports cleanly

---

payu/manifest.py

Fixes https://github.com/payu-org/payu/issues/201

201: Added check for scaninputs in non-reproduce branch

---

payu/experiment.py

Fixes https://github.com/payu-org/payu/issues/205, I think.

Fix attempt to delete restart folder that is a symbolic link.

---

.circleci/config.yml
conda/meta.yaml
setup.py

Trying to get circle building correctly.

Changed to remove python version from CircleCI build

---

.circleci/config.yml
.gitignore
payu/scheduler/pbs.py
setup.py
test/test_pbs.py

Fix error when shortpath does not have trailing slash

---

.circleci/config.yml
docs/source/config.rst
payu/experiment.py

Add model error user script hook

---

docs/source/config.rst

Added documentation for restart option. Fixes #249

Document restart option

---

docs/source/usage.rst

Added documentation for stop_run semaphore file fixes #226

Documented stop_run

---

payu/cli.py
payu/experiment.py
payu/subcommands/run_cmd.py

Fixes #255 bug
Previous PR did not propagate the new force flag to PBS jobs

Propagated force flag to PBS jobs

---

.travis.yml
test/requirements_test.txt

Coveralls is reporting no coverage, try and get it working.

Try and get coveralls working

---

.travis.yml

Added some debugging to check .coverage file persists

Another attempt to get coveralls working

---

docs/source/usage.rst

see https://github.com/payu-org/payu/issues/275

clarify payu collate documentation

---

docs/source/config.rst
payu/models/um.py

I've noticed runspersub config entry is not documented.
Closes #280

Add doc for runspersub

---

.github/workflows/CI.yml
payu/models/fms.py
test/models/test_fms.py

Update CI python versions

---

docs/source/config.rst

closes https://github.com/payu-org/payu/issues/337

document modules

---

payu/experiment.py
test/test_prune_restarts.py

There's a bug in the `get_restarts_to_prune()` method which raises an error when `restart_history` is configured and an archive directory exists but it contains no restarts. 
I've added a test case that was able to recreate the error.
I could also do an early return if there is no restarts, but I've left the check for it later in the method to after checks for valid `config.yaml` values. But it would be an easy change to add that. 
Closes #422

Add bug fix for restart history with empty archive directory

---

payu/models/cesm_cmeps.py

Quick bug fix that closes #472

CesmCmeps: check work_restart_path exists before trying to archive it

---

payu/experiment.py

Always map-by `node` using user-supplied `npernode`

---

payu/experiment.py
payu/models/__init__.py
payu/models/model.py
payu/models/roms.py

Closes #622  
This is rebased on top of the netCDF4 dependency change that broke readthedocs in #623

Add ROMS driver

---

.github/workflows/CI.yml
payu/branch.py
payu/git_utils.py
payu/subcommands/sweep_cmd.py
test/common.py
test/test_cli.py
test/test_git_utils.py
test/test_setup.py

Check for detached HEAD state and raise an exception.
Where appropriate catch exception and suggest appropriate remedy.
Fixes #625

Raise exception when repo is in a detached HEAD state
