docs/source/config.rst, docs/source/usage.rst, payu/cli.py, payu/experiment.py, payu/subcommands/args.py, payu/subcommands/collate_cmd.py
Hey Marshall,
I had a crack at implementing the option to directly specify a collate directory. 
I did a few quick tests, and it seems to work from payu collate and payu-collate. 
I'm not sure if this is the way you would have done it, or if I might have broken something else. In any case, have a look, and tell me what you think.
It has another use I hadn't thought about: collating restarts for changing processor count/layout.
Cheers
=> Added option to directly specify collate directory

payu/runlog.py
The git dependency thing was tripping me up a lot and I saw an easy way around it.
If the cwd flag for subprocess isn't desirable then don't merge.
I also changed the import statement for subprocess to match (most of) the rest of the code
=> Removed dependency on git -C

payu/cli.py, payu/experiment.py, payu/models/fms.py, payu/subcommands/collate_cmd.py
Paul's collation jobs were taking a long time, he was saving at high temporal resolution and doing ensembles, and my high temporal resolution 0.1 deg sims were taking 12+ hours to collate, so this is a fix of sorts.
I think it would be better to submit multiple collate jobs, but that would have been a bigger change, so I settled for using multiprocessing to submit multiple jobs within one collate job.
This adds config option collate_ncpus, to specify the number of cpus to be requested for the collate PBS submission.
The drawback is that multiprocessor jobs can't be submitted to the copy queue on raijin, so normal or express must be specified. Care must be taken to also request enough memory for multiple collate jobs to run simultaneously.
There was a bug in the '-d' directory path …
=> Added parallel collation for fms and fixed a small bug in '-d' implementation

payu/models/fms.py, payu/subcommands/collate_cmd.py
Previous version didn't work when submitted as a batch job because of a dumb error I introduced. Should have checked that.
The only substantial revision is to make fms.collate respect the collate_ncpus setting from config. This wasn't the case in the previous version. That config was only used in the batch version, which sets up the number of CPUs for the job and fms.collate just grabbed the number of CPUs from the environment.
So now payu-collate does (collate_cmd.py) does a (slightly bodgy) test to see if we're in a PBS environment (not strictly necessary I guess ... ) and then sets an environment variable to pass this information on to fms.collate.
Marshall, maybe you'd prefer not to do that bodgy test and just set the environment variable? I tried looking in the run command to find an …
=> Made payu-collate respect collate_ncpus from config. Fixed bug introduced in last commit: referencing unknown variable

payu/models/fms.py
Addressing https://github.com/marshallward/payu/issues/73
I'm not entirely sure why I let this just go through, I guess we're sanguine about a collation failing, and will want to still collate other files if possible. It is up to the user to check and maybe alter resources for the collation step.
=> Added explicit exception catching to cmdthread in fms.py

payu/models/fms.py
- Format is netCDF4 (-n4)
- Compress outputs (-z)
- Fill masked processor tiles with FillValue (-m)
=> Changed default FMS collate flags

payu/envmod.py, payu/models/access.py, payu/models/cice.py, payu/subcommands/run_cmd.py
Added a config option `nrunspersub` to run multiple model runs for each PBS submission which addresses https://github.com/marshallward/payu/issues/84
Implemented this as a parameter in `config.yaml` as it affects the choice of PBS parameters, i.e. `walltime`.
This option respects the existing `-n` method of specifying multiple model runs, as `n_runs` is decremented as normal.
I did try specifying the number of resubmits as a command line option, but I don't think it works as well.
=> Add option for multiple runs per PBS submit (runspersub)

payu/models/fms.py
Return error codes from FMS collation and report them to stderr at the end. 
Exit payu with error if any collation fails.
=> Check return codes of FMS collation more closely

payu/models/cice5.py
This is a fix for https://github.com/marshallward/payu/issues/99
The number of iced restarts grows with time because they aren't all properly deleted. I think the previous logic assumed only one restart needed to be deleted. In the case where more than one restart was created the number of restarts would grow.
I have tested with a 1 deg ACCESS-OM model and this is the listing of restarts after 4 resubmissions
```bash
ls  -1 archive/restart27[2-7]/ice/iced.*
archive/restart272/ice/iced.0541-04-01-00000.nc
archive/restart273/ice/iced.0541-05-01-00000.nc
archive/restart274/ice/iced.0541-06-01-00000.nc
archive/restart275/ice/iced.0541-07-01-00000.nc
```
So one restart for every restart directory. I had a feeling that `CICE` could use multiple restarts, but I can't recall why I think this.
Any …
=> Fix issue #99, number of ice restart files growing with time

payu/experiment.py, payu/models/__init__.py, payu/models/access.py, payu/models/accessom2.py, payu/models/model.py, payu/models/yatm.py
The coupled model config now looks like the below, which I think is an improvement. There is a bit of hackery to deal with the fact that the top level model is treated differently in payu to the submodels. Going forward perhaps we could remove this distinction? I think it was probably me who did this in the first place to get ACCESS working ... not sure it was the right approach. 
Notice no more oasis model, also access-om2 model has some common files. 
```
model: access-om2
input: common_1deg_jra55
submodels:
- name: atmosphere
model: yatm
exe: yatm_2362fd31.exe
input: yatm
ncpus: 1
- name: ocean
model: mom
exe: fms_ACCESS-OM_3f58ddc6.x
input: mom_1deg
ncpus: 216
- name: ice
model: cice5
exe: cice_auscom_360x300_24p_a6bce947.exe
input: cice_1deg
ncpus: 24
```
=> ACCESS-OM2 driver support separate from ACCESS driver. #101

payu/experiment.py, payu/fsops.py, payu/manifest.py, payu/models/model.py, payu/runlog.py, payu/subcommands/args.py, payu/subcommands/run_cmd.py, payu/subcommands/setup_cmd.py, setup.py
Add input/restart and executable file tracking to payu using the yamanifest module to create YaML based manifest files which are tracked by git. 
When they exist, manifest files are used to populate the input directories, restarts (when required) and links to the executables. This should allow for easier configuration sharing, as the experiment just needs to be cloned and can be run without further configuration changes.
=> Add file tracking to payu

payu/models/mitgcm.py
Parse MITgcm config files to check they are correct namelists adding to list self.config_files.
Addresses https://github.com/marshallward/payu/issues/148.
=> Parse MITgcm config files to check they are correct namelists

payu/manifest.py
When starting from initial conditions from a control directory that has a restart manifest, e.g. after running `payu sweep --hard`, the `manifests/restart.yaml` file was not over-written.
This fixes this by setting the `needsync` flag.
=> Ensure restart file is always written when not reproducing.

payu/models/fms.py
This will collate the previous restart, to avoid issues with half
collated restarts if collate doesn't complete before next run starts.
Also avoids any possible speed hit when using collated restarts.
This is basically https://github.com/marshallward/payu/pull/125/commits/1039acc9442ad2cada967cbbfbc07936cc0a46ce but applied to the previous restart.
I don't know why, but that other PR was merged, but then overwritten at some stage.
=> Add option to collate restart files as well as output files

payu/experiment.py
Forgot to prepend error path to logs when run crashes.
Now use git commit hash to uniquely identify logs if PBS id not
available, e.g. using payu-run.
=> Cleanup some errors in cleanup code introduced in recent commits

payu/models/cice.py, payu/models/cice5.py, payu/runlog.py
Added support for splitting input and restart directories in the `cice5` driver (actually mostly in the `cice` driver but there is no `cice4` version that supports this)
The `cice5` code change is here:
https://github.com/OceansAus/cice5/commit/465494bb551ec15ec3ec82308359e6c7d3ae28a5
This change tries to be backwards compatible. I have tested on an access-om2 1 degree model and it seems to work fine.
To use this you also need to make a couple of changes to the cice_in.nml file:
Must add this to `&setup_nml`
```
input_dir      = 'INPUT/'
```
and change all instances of paths with `RESTART` at the beginning, to `INPUT`
```
pointer_file   = 'INPUT/ice.restart_file'
grid_file    = 'INPUT/grid.nc'
kmt_file     = 'INPUT/kmt.nc'
```
=> Added support for ability of cice5 to define separate input and restart directories.

payu/manifest.py
Used all paths instead of just the paths of the changed files. Fixed
=> Introduced bug in check_fast when fixing the previous fullpath bug.

payu/manifest.py, payu/models/access.py, payu/models/model.py, payu/models/oasis.py, payu/models/um.py, payu/subcommands/run_cmd.py
Added explicit `um_calendar.res.yaml` file from which to restart the UM, rather than reading in prior version of `namelists`. This breaks a dependency on a prior output directory.
Fixes https://github.com/marshallward/payu/issues/168
`namcouple` is not required for model time restarts, so is not copied to restarts, but instead is archived in output.
=> Altered UM restart calendar handling

.travis.yml, payu/models/mitgcm.py
Can change timestep within a run and maintain correct model time and step number.
Uses a yaml restart file to save the model end time for the current
run which is read in by the next run.
=> Updated MITgcm calendar handling

payu/models/um.py
Removed setting
cable_user%CABLE_RUNTIME_COUPLED = .FALSE.
in CABLE namelist. Caused non-bit reproducibility with ACCESS-ESM-1.5 runs.
=> Removed setting CABLE_RUNTIME_COUPLED false in nameless

docs/source/conf.py
`man_pages` is being declared twice, so one of the values is not used. I left the last one, as that's probably what's being used now.
=> Remove duplicate key

payu/manifest.py
Hi!
Small change to prevent unwanted behaviour for `add_fast`. https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html
Cheers
=> Avoid mutable default parameters

payu/subcommands/run_cmd.py
Initialise manifest in run_cmd for subruns, otherwise previous restart can remain in the manifest.
Addresses https://github.com/payu-org/payu/issues/188
=> Previous restarts polluting restart manifests with subruns

payu/scheduler/pbs.py, setup.py
Added retry decorator (from tenacity) to get_qstat_info as calls to qstat were timing out and bringing down simulations with multiple runs per submit.
=> Make get_qstat_info more robust

.circleci/config.yml, .travis.yml, README.rst, conda/meta.yaml, payu/cli.py, payu/envmod.py, payu/experiment.py, payu/laboratory.py, payu/manifest.py, payu/models/__init__.py, payu/models/mitgcm.py, payu/models/model.py, payu/models/mom.py, payu/models/test.py, payu/scheduler/pbs.py, payu/subcommands/profile_cmd.py, payu/subcommands/run_cmd.py, setup.py, test/common.py, test/requirements_test.txt, test/test_manifest.py, test/test_payu.py
Added test model for ... testing. Has minimal requirements and means
tests can be independent of model driver implementation. A platonic
ideal if you will.
Added config options for fine-grained reproduce options. Input, exe
and restart reproduce can be turned on independently of each other.
Added extensive testing of init/setup and reproduce.
Fixes https://github.com/payu-org/payu/issues/203
=> Fine-grained reproduce flags and testing

payu/models/mitgcm.py
Removed trailing comma which made restart a tuple, stuffing up the restart file
Fixes #207
=> Fix borked restart file

payu/envmod.py
Fixes https://github.com/payu-org/payu/issues/209
On `gadi` `MODULE_VERSION` environment variable is no longer set by default, but `MODULESHOME` is. This change checks for `MODULESHOME` before trying to generate it from `MODULE_VERSION`.
=> Check for MODULESHOME environment variable for gadi support

.travis.yml, payu/laboratory.py, test/common.py, test/test_manifest.py, test/test_paths.py
Added logic to choose 'short' or 'scratch' as default shortpath location depending on which exists
Added tests for lab path creation.
Rearranged existing tests and shared code to common.py
=> Added logic to choose 'short' or 'scratch' as default shortpath location

.travis.yml, payu/cli.py, payu/envmod.py, payu/experiment.py, payu/fsops.py, payu/manifest.py, payu/models/model.py, payu/scheduler/pbs.py, payu/subcommands/run_cmd.py, test/common.py, test/test_manifest.py, test/test_paths.py, test/test_pbs.py
Fixes https://github.com/payu-org/payu/issues/215
=> Added routine to return correct storage string and test

.travis.yml, payu/manifest.py, test/common.py, test/test_manifest.py, test/test_paths.py, test/test_pbs.py
Added tests for specifying hashes.
Fixed bug with test/models/test_mitgcm.py that globally changed
config. Now specify config to write and make deep copies where
appropriate.
Changed common input in tests to make local import.
Fixes #233
=> Added capability to specify hash functions for manifest

.circleci/config.yml, conda/meta.yaml, docs/source/manifests.rst, payu/experiment.py, payu/fsops.py, payu/models/fms.py, setup.py, test/common.py, test/requirements_test.txt, test/test_payu.py
Use new function to move contents of the ephemeral `work` directory to a new `output` directory in `archive`.
Fixes #238
=> Move work directory contents to new output directory

payu/scheduler/pbs.py, test/test_pbs.py
Fixes #245 
Uses the mount point being scanned for to find the next path element that is the project code required.
=> Add support for legacy mount points on gadi

payu/cli.py, payu/experiment.py, payu/subcommands/args.py, payu/subcommands/collate_cmd.py, payu/subcommands/run_cmd.py, payu/subcommands/setup_cmd.py, test/common.py, test/test_cli.py, test/test_setup.py
Added force option to setup and run. Automatically removes existing work directory. Closes #255.
Also hanged default of reproduce option to False from None.
=> Added force option to setup and run

docs/source/conf.py, docs/source/usage.rst
Fixes #255 missing documentation
=> Added documentation for force flag

.travis.yml, payu/models/mitgcm.py, test/models/test_mitgcm.py
Changed to floating point division in MITgcm to avoid issues with floating point round off with fractional timesteps.
Added mitgcm model tests.
Fixes #228
=> Changed to floating point division in MITgcm to support fractional timestep

payu/models/mitgcm.py, test/models/test_mitgcm.py
Added logic branch to support changing model time step when new timestep is not a divisor of current runtime. Does so by changing basetime.
Added test.
Closes #263
=> MITgcm: Support changing model time step when non-integer divisor

payu/models/model.py, test/test_manifest.py
=> Fix bug overwriting exe manifest on reproduce

payu/subcommands/collate_cmd.py, payu/subcommands/profile_cmd.py, payu/subcommands/run_cmd.py
Fixes #268 
Options were not being properly propagated due to not specifying arguments correctly when calling cli.set_env_vars
=> Use keyword arguments for calls to cli.set_env_vars

.github/workflows/CI.yml, payu/experiment.py
Closes #289 
Add logic to run the `postscript` action for jobs which do not collate, which ensures `postscript` will *always* run once an output directory is guaranteed not to change as a result of an action by `payu`.
Tested and works fine. Not sure if there is a simple `pytest` I could add for this unfortunately.
=> Add postscript action to non-collate jobs

payu/fsops.py, test/test_payu.py
If one passes an empty YAML file, e.g. all lines commented out, then
PyYAML returns `None`, which breaks subsequent assumptions in the
handling of config.
We now parse an empty file as an empty dict, {}.
=> Empty YAML config handled as empty dict

payu/models/cice.py
Closes #303 
Moved cice calendar manipulation inside logic which ensures this is only used for drivers which set the run calendar in config.yaml, i.e. access
Will only fix calendar overflow issue for `accessom2` driver. Issue will persist for the `access` driver, but this is no longer widely used.
=> Fix bug with years > 10000 for accessom2

payu/models/fms.py, test/models/test_fms.py
Closes #309 
Modified payu.models.fms.get_uncollated_files to support > 9999 files.
Added tests.
=> Fix FMS collate for >9999 files

payu/models/fms.py, test/models/test_fms.py
Fixes #316 
PR #310 broke collating restart directories because of the extra ``.res.`` "suffix" when using suffixes in the new method.
Indexing backwards seems to work. Added tests which are passing.
=> Fix collating restarts

payu/models/mom6.py
At some point last year, SIS2 stopped ignoring its namelist for input filenames. I think this effectively meant that every run segment was starting with no ice. If the `SIS_input_nml` is present, it should get the same input type (i.e. restart or new run) as MOM6 itself.
=> Tell SIS2 about restart runs for MOM6

payu/models/mom6.py
Using the mechanism to point to an external restart directory:
```yaml
restart: /path/to/restart
```
doesn't modify the experiment counter, because as far as payu is concerned, this is the first run. This breaks the logic the MOM6 module was using to determine whether to flag a run as a restart or not. In the case that the prior restart path has been set, we want to explicitly perform a restart run.
Thanks to @julia-neme for (unfortunately) finding this!
=> Flag a MOM6 run as a restart if using prior restart path

.gitignore, payu/envmod.py, payu/experiment.py, payu/fsops.py, payu/models/fms.py, test/resources/sample_ldd_output.txt, test/test_payu.py
Change logic in experiments  to default to adding `-wdir` to the arguments given to mpirun. 
Should close #341 and close #350
=> Default to add '-wdir' arguments 

payu/experiment.py, payu/fsops.py, payu/models/model.py, payu/schedulers/pbs.py, test/test_pbs.py
Store information of required libs per binary on the Model object if there exists an executable path. 
Should close #354 and #355
=> Store required libs on model object

.github/workflows/CD.yml
Add automated PyPI publishing to CD Workflow.
Closes #361
=> Add pypi build and publish to CD

payu/models/cesm_cmeps.py
The WW3 model definition file input needs to be in the work directory and called `mod_def.ww3`. Previously this driver looked for a file in the inputs with "mod_def.ww3" in the filename and then copied that file to the work directory. This is bad practice. Now, the name of the file is assumed to be "mod_def.ww3" and this file is symlinked instead. Those setting up the configuration will need to ensure that a file with the right name is included in the inputs (e.g. using a symlink if the original input has a different name).
Closes #365
=> Symlink instead of copy the `mod_def.ww3` input in the cesm_cmeps driver

payu/experiment.py, payu/models/model.py, test/common.py, test/test_manifest.py
- Fix to payu crashing with empty restart files/dirs
- Add default values of LD_LIBRARY_PATHS
- Raise exceptions for missing model executables
Closes #285, closes #307, closes #306
=> Refactor experiment.set_counter() and some minor bug fixes

payu/experiment.py
Explicitly check for None in set_counter if-statements, to set counter correctly when max restart/output index is 0 
Should close #369
=> Fix bug in set_counter

payu/models/mom6.py, test/common.py, test/models/test_mom6.py
In this branch, I've tagged on some code that runs at the end of `Mom6.setup()` that checks if files listed in `parameter_file` of `MOM_input_nml` and `SIS_input_nml` namelists in input.nml, are included in mom6's hard coded `config_files` or `optional_config_files`.
If the file is not present, I've added a warning, added the file to `config_files` and then copied the file to the workpath.
Or is just a warning/error printed out during setup sufficient? If not, should the files be treated as `config_files` or `optional_config_files` - i.e. raises an exception if file not found or not?
From what I can tell, the only usages of `optional_config_files` and `config_files` are:
- to be added to the runlog manifest (which happens during Experiment.run())
- config files are copied from the control …
=> Add a check for MOM6 parameter filenames defined in input.nml

payu/models/cesm_cmeps.py, payu/models/model.py, payu/models/mom6.py, test/models/test_mom6.py
Refactored the code added in #364, so it can also be re-used for the `mom` component in `cesm-cmeps` driver.
I didn't add in `mixin` class in the end, as it just needed only one function (`mom6_add_parameter_files`) which I broke out of `mom6` driver class. Though please let me know if using a `mixin` class would still be better!
Should close #371
=> Read mom6 parameter files in cesm cmeps driver

payu/models/mom6.py, test/models/test_mom6.py
Closes #380.
Small fix in mom6 driver. Ensuring config files are copied to work path before any patches to `input.nml` are written.
Added another test
=> Fix bug copying mom6 config files introduced in #373

conda/meta.yaml, test/models/test_mom6.py
Small change here adding cftime run dependency to `conda/meta.yaml`. This in used in date based restart pruning.
There's also a fix for a small bug in testing which creates a `work` directory in payu. Moved setup call so it runs inside the temporary test control directory.
=> add cftime dependency to conda meta.yaml

.github/workflows/CI.yml, conda/meta.yaml
In this PR:
* Updating the `meta.yml` file to require `python <=3.11` so we can `import imp`. 
* Updated the CI pipeline to attempt to build `payu` via `conda` as well, so we can catch future errors of the above sort before we merge into `master`. 
Closes #395
=> Conda Deployment Fix

.github/workflows/CD.yml
The PyPI upload stopped working after #403 was merged. I can't say I understand why as #403 didn't touch the workflow steps that are causing the problem... Regardless, this PR should fix things.
The update to `actions/upload-artifact@v4` (from `v3`) is not necessary to fix the issue, but good to do anyway.
Closes #398 (again)
=> Fix PyPI upload

payu/_version.py
Removes the "v" `tag_prefix` from `_version.py` (by reinstalling `versioneer`: `versioneer install --no-vendor`). This was preventing the version from being determined correctly in readthedocs builds.
Closes #398 (again again)
=> Update tag_prefix in _version.py

payu/models/um.py
Fix is to remove the restart files from the work directory after the last one is copied.
Previously in `archive/pre-industrial/output000/atmosphere` there were 12 monthly restart files `aiihca.daa*`
```
% ls ai*
aiihca.daa1210  aiihca.daa1c10  aiihca.paa1may  aiihca.pea1jun  aiihca.pga1jan
aiihca.daa1310  aiihca.daa2110  aiihca.paa1nov  aiihca.pea1mar  aiihca.pga1jul
aiihca.daa1410  aiihca.paa1apr  aiihca.paa1oct  aiihca.pea1may  aiihca.pga1jun
aiihca.daa1510  aiihca.paa1aug  aiihca.paa1sep  aiihca.pea1nov  aiihca.pga1mar
aiihca.daa1610  aiihca.paa1dec  aiihca.pea1apr  aiihca.pea1oct  aiihca.pga1may
aiihca.daa1710  aiihca.paa1feb  aiihca.pea1aug  aiihca.pea1sep  aiihca.pga1nov
aiihca.daa1810  aiihca.paa1jan  aiihca.pea1dec  aiihca.pga1apr  aiihca.pga1oct
aiihca.daa1910  aiihca.paa1jul …
```
=> Prevent UM restart files being archived to output

docs/source/config.rst, payu/metadata.py, test/test_metadata.py
This PR fixes the config option to disable metadata bug #426.
I’ve added a test that replicates the error. 
Closes #426
=> Add fix and test for metadata enable false bug

payu/metadata.py, test/test_metadata.py
In #420, there’s a bug with using branching logic, where an existing experiment is not detected if its archive does not exist. So if an experiment was created then deleted on a branch in a control directory that has a corresponding legacy archive,  subsequent `payu setup/run` calls, it’ll use the legacy archive. 
This PR so far adds an additional check when checking for the existence of archives, also check for metadata with a matching UUID. 
This isn’t a perfect check as it requires `payu setup/payu run/ payu checkout` to be run on the legacy experiment which will then subsequently create a UUID and metadata in the legacy archive if it doesn’t already exist. Otherwise, if there is no metadata associated with the legacy archive and a new UUID has not been generated, it’s difficult to know …
=> Add check for UUIDs when checking for existence of archives

payu/models/cesm_cmeps.py
MOM6 may split its restart across multiple files. This wasn't accounted for in the `cesm_cmeps` driver, but with this PR it is.
Closes #430
=> Allow for multiple restarts from each component in `cesm_cmeps` driver

payu/metadata.py
This PR updates the metadata schema used by `metadata.py` to [experiment-metadata/1-0-3.json](https://github.com/ACCESS-NRI/schema/tree/main/au.org.access-nri/model/output/experiment-metadata/1-0-3.json)
Closes #424. Related #429
=> Update metadata schema url

payu/branch.py
As described in issue #431, added extra message when directory to clone to already exists, 
and if there is an incomplete checkout, remove the cloned directory and add an additional error message.
It only removes directory in incomplete checkout command if the custom PayuBranchError is raised. I didn't make it general as there could be errors post-checkout like config.yaml not existing - In this case no metadata is created. 
Closes #431
=> Add additional error messaging to payu clone #431

payu/envmod.py, payu/experiment.py, payu/models/fms.py, payu/models/model.py
- Move setting executable paths in Model class to Experiment.setup()
- Inspect user modules (specified in config.yaml) to changes to PATH - The modules are restricted to user module directories defined in config.yaml
- If exe is not an absolute path, search along above paths
Modules are still loaded the same way in experiment.run so to not change users env vars when running `payu setup` 
Closes #379
=> Get module executables from path loaded by environment modules

payu/models/cesm_cmeps.py, test/models/test_cesm_cmeps.py, test/resources/nuopc.runconfig
This is a ~work-in-progress~ PR with changes required to allow running generic_tracers in MOM with the `cesm_cmeps` driver. ~This PR is still under development and is likely to change. I'm only opening now for visibility and to help me keep track of the various changes I'm having to make across multiple repos to allow this functionality.~
Changes made:
- **BREAKING CHANGE**: input directory in work directory renamed to `INPUT` (from `input`). This is because unfortunately `INPUT` is hardcoded in some parts of FMS that are used by generic tracers.
- This model uses "pointer files" to keep track of most restarts. However, when generic tracers are used, there are additional restarts that do not have pointer files. These are written to an `additional_restart_dir` that is specified in the …
=> Allow generic tracers with `cesm_cmeps` driver

payu/experiment.py, payu/subcommands/run_cmd.py
Add environment variables of experiment output paths, and run counters so they can be easily accessed via user-scripts.
Currently have added `PAYU_CURRENT_RUN`, `PAYU_ARCHIVE_DIR`, `PAYU_CURRENT_OUTPUT_DIR` and `PAYU_CURRENT_RESTART_DIR`.
Closes #443
=> Save experiment outputs + counters as environment variables

payu/models/um.py
Changes related to #419.
Payu currently requires several UM configuration files which aren't required and duplicate settings in the required ones, making it confusing to modify the correct namelists. 
I've removed the unneeded files from the `config_files` in `um.py`, though kept `parexe` as an `optional_configuration_file` in case it is needed by older configurations.
=> Remove unnecessary UM config files

payu/models/um.py
Closes #454
[`um.py`](https://github.com/payu-org/payu/blob/master/payu/models/um.py) currently sources a python file [`um_env.py`](https://github.com/ACCESS-NRI/access-esm1.5-configs/blob/pre-industrial/atmosphere/um_env.py) in order to set environment variables by the UM, which might cause security issues. This pull request makes payu read the data from a yaml file instead.
If this ends up being merged, we'll need to also convert the `um_env.py` files in the configurations to yaml.
---
Printing out the environment through a run stage userscript shows that the relevant environment variables are the same with and without the changes:
Printed UM environment variable values without the changes:
<details>
```
AINITIAL=
ASTART=restart_dump.astart
AUSCOM_CPL=true …
```
=> Replace UM um_env.py configuration file with yaml file

payu/experiment.py, payu/fsops.py, test/test_payu.py
- Raise RuntimeErrors when user-scripts exit with an error (previously it was just a warning)
- Move run user-script code to payu.fsops out of Experiment class so it's easier to test
- Use shell=True for subprocess commands needing a shell, e.g. file redirections, pipes
- Add tests for running userscripts
To be able to run commands such as `echo "some_data" > input.txt` that are in payu documentation, it requires use of `shell=True`. So there's some security issues with using `shell=True` (https://docs.python.org/3/library/subprocess.html#security-considerations). However as the user scripts have typically been user defined `.sh` files run with `/bin/bash`, it could contain malicious code anyway..
I added a `needs_subprocess_shell` function that checks for any shell specific values. The …
=> User-scripts error-handling, commands and tests

payu/experiment.py
This pull request covers initial work for #463.  
Allowing both syncing and NetCDF conversion for ESM simulations will be easier if the NetCDF conversion is run as a payu postscript, rather than as a userscript. This pull request adds in shell requirement checks and environment variable exports to the postscript submission, which are needed for the NetCDF conversion script.
=> Add environment variables and shell checks for postscripts

payu/models/access.py, payu/models/accessom2.py, payu/models/mom.py
Closes #464 
This pull requests adds support for date based restart pruning for ESM1.5, which was previously implemented for the MOM models. As ESM1.5 uses MOM as a submodel, and produces the same ocean date files `ocean_solo.res` in the restart directories, I've just copied the `get_restart_datetime` method from `mom_mixin.py` into `access.py`. 
I've manually tested it with with different monthly and yearly restart frequencies. E.g. running in month long sections, with `restart_freq: 3MS` for a total of 10 month results in the following archive:
```
metadata.yaml  output000  output001  output002  output003  output004  output005  output006  output007  output008  output009  pbs_logs  restart000  restart003  restart006  restart009
```
Likewise running for 6 months with `restart_freq: 2MS` …
=> Adding date based pruning for ESM

.github/workflows/CI.yml
Closes #453
Update coveralls action to point a commit with a fix for dubious git ownership errors when running parallel coveralls step - e.g. https://github.com/AndreMiras/coveralls-python-action/commit/65c1672f0b8a201702d86c81b79187df74072505
This commit is merged into the `develop` branch on the `coveralls-python-action` repository, but not yet the main branch, and there hasn't been a tag released version update since 2020.
Another option is to use code-cov for this project which is used in other projects? https://github.com/ACCESS-NRI/dev-docs/wiki/Continuous-integration-and-deployment#uploading-code-coverage-reports-to-codecov
=> CI coveralls parallel fix

.github/workflows/CI.yml, payu/cli.py
A `distutils.sysconfig` import was used in `payu/cli.py`. `distutils` is now deprecated and has been removed in Python 3.12. The PR replaces `distutils` with the `sysconfig` standard library (as recommended here: https://peps.python.org/pep-0632/#migration-advice).
I've also added Python 3.12 to CI tests. Keeping the Python 3.9 tests at this stage as Python 3.9 is still currently used in the `vk83`'s payu environments on NCI. 
Closes #476
=> Replace deprecated `distutils` dependency

payu/envmod.py, test/test_envmod.py
Allow checks for "modules: load:" modulefiles to allow when there's an exact match in available modules. This is to fix bug #481 where module avail for `openmpi/4.1.5` includes `openmpi/4.1.5` and `openmpi/4.1.5-debug`.
I've also added tests for parsing module avail output.
Closes #481.
@aidanheerdegen last week there was an issue with multiple modules found in `/g/data/vk83/modules` and `/g/data/vk83/modules/access-models`, even though they were the same modulefile. I noticed in the modules docs there's a `module paths` command that lists paths of available modulefiles matching a pattern so for the above, it would still evaluate to the same path. There's a couple of differences to `module avail`:
-  Running the command `module paths` using `modulecmd` (`$MODULESHOME//bin/modulecmd`) …
=> Update check for load user modulefiles to allow  exact match

payu/branch.py, payu/cli.py, payu/fsops.py, test/test_payu.py
As suggested in this issue #441,
- Add warnings when reading config.yaml files with duplicate keys (as PyYAML library silently over-writes the value with the subsequent value) 
- When adding restarts to config.yaml when creating a new git branch, allow duplicate keys but still warn that they will get deleted when the config.yaml file gets modified (note the subsequent key will get deleted). Ruamel yaml library is used for modifying the config files as it can preserve multi-line strings and comments.
- Added a test for testing the warnings above
Closes #441
By default warnings are formatted with a line of the source code, e.g. the line `warnings.warn(` in
```
/home/189/jb4202/payu_fork/payu/fsops.py:83: UserWarning: Duplicate key found in config.yaml: key 'model' with value 'mom6' …
```
=> 441 inconsistency between yaml libs bugfix

payu/models/access.py, payu/models/cice.py, payu/models/cice5.py, test/models/test_cice.py
To enable simpler changes to the icefields namelist in cice, this change adds support for an `ice_history.nml` file which is spliced into the normal cice runtime settings (`cice_in.nml`) by payu before the model is run.
This follow the discussion in https://forum.access-hive.org.au/t/access-esm1-5-release-work-plan/1721/24
The contents of ice_history.nml can be anything which also would fit in cice_in.nml , but the intention is to move &icefields_nml to the ice_history file
Do we need to update docs ? Or tests ? There doesn't appear to be any of either at this point
=> Enable seperate ice_history.nml & cice_in.nml settings

docs/source/config.rst, docs/source/manifests.rst, payu/manifest.py, payu/models/model.py, payu/schedulers/pbs.py, test/common.py, test/test_manifest.py
Ok so I've had a go changing the manifests reproduce True logic. Currently (on the main branch), it create symlinks to the work directory from the manifests, and only raise errors if the files that existing on the manifest are modified.
In the first commit, I changed logic in model setup to always add model exe path and prior restart path to the manifest. This picks up if exe path is changed in `config.yaml`. If there's new restart files, in the prior restart path, it will also pick it up that there's been a change.
It still had the logic that symlinks from files to the work directory are generated from the manifest initially when reproduce is True. This could run into weird issues when there's a file in the manifest, thats existing unchanged on the filesystem, but it's no longer added to …
=> Manifest Reproduce true fix

payu/experiment.py, payu/metadata.py, payu/subcommands/args.py, payu/subcommands/setup_cmd.py, payu/subcommands/sweep_cmd.py, test/common.py, test/test_cli.py, test/test_metadata.py
Add cmd line flag `--metadata-off`/`-M` (better names?) to payu subcommands to disable metadata files or UUIDs being created. This uses control directory for experiment names. (so equivalent to `metadata: enable: false` in `config.yaml`)
Added this flag to sub-commands that create an Experiment class instance - so archive, collate, profile, run, setup, sweep and sync. 
Closes #446
=> Add cmd-line flag to disable metadata + UUID generation and commits

payu/models/um.py
Small change - changing the error type to `RuntimeError` and edited error message for `um_env.py` files  - as discussed in #485. @blimlim would you be OK to review this? 
Closes #485
=> Change error type and message for UM um_env.py

.github/workflows/CI.yml, conda/meta.yaml
Remove Python 3.9 from CI tests, and update minimum python in `run` requirements in conda meta.yaml. 
Closes #497
=> Drop Python 3.9 

payu/laboratory.py, test/test_paths.py
Closes #502 
If `project` is defined in `config.yaml`, use this project for default shortpaths. This is to prevent a mismatch of default shortpath when running commands on a login-node vs on a PBS `payu run` submission.
I also refactored the tests for laboratory basepaths to make each test a bit more isolated. I also added a couple more test cases.
=> Default shortpath project bug

.readthedocs.yaml, docs/source/conf.py
As brought up in #494, the `readthedocs` versions are `1.1.5+0.g78f67ff.dirty` for `1.1.5`. I think the reason why is due to new files during added during readthedocs build (`docs/source/_build/` and `_readthedocs/`), and auto-generated content is added to `docs/source/conf.py`. Due to these modifications in the repository, when payu is imported in `docs/source/conf.py`  and the version is determined,  `versioneer` marks the versions as `dirty`.
To prevent this, I've added an local pip install of `payu` to run before the docs build step, so the version is unaffected by the modified files. The documentation build for this PR now has no `dirty` tag: https://payu--505.org.readthedocs.build/en/505/.
With some local testing, if an `1.1.5` tag is checked out, there a modification to a file and …
=> Readthedocs version tag

docs/source/config.rst, payu/experiment.py, pyproject.toml, test/test_setup.py
Add a `payu_minimum_version` option to `config.yaml`. This runs a check at the start of the `Experimet.setup` comparing the current payu version and raises a `RuntimeError` if version is earlier than the configured minimum version.
I added a dependency on the `packaging` lib to parse and compare versions, which seems to the recommended library for parsing version strings (https://stackoverflow.com/a/11887885, https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html#prefer-setuptools). I could do some regex parsing, but this library can handle already handles versions like `1.0`, `v0.1`, `1.0.0+4.gabc1234`  etc. So hopefully it'll be less buggy and will be able to support future version formats..
I added the check to the start of the setup method to the experiment class which …
=> Add minimum payu version check 

payu/git_utils.py, test/test_git_utils.py
In #405, `payu checkout` raises an error when it is no longer able to fetch branches from the remote repository. This happens when cloning from a remote repository using a path, and then that path gets deleted at a later point of time.
I changed it to catch the exception, and to display a warning to the user instead that payu was not able to fetch from the remote repository.
=>  Fix missing origin repository bug

payu/models/cice.py, payu/models/cice5.py, test/models/test_cice.py, test/models/test_cice5.py
Attempts to close #499 
This pull request modifies the `cice.py` driver, by pulling the timing calculations out from `setup()` into a separate `calc_runtime()` method. This method is then overridden in the `cice5.py` driver,  allowing the `cice_in.nml` namelist file to be absent from the restart directory, since OM2 does not use the information from these calculations. This in turn will allow OM2 to be run after using `payu clone -r` with a specified OM2 restart directory.
Most of the code changes are in the tests, which require a bit of intricate set up. Given that we're skipping `payu setup` and directly running `model.setup()` (in order to avoid more complicated pre-test setup), it's difficult to know how well we've matched the conditions for setting up a real experiment. E.g. When …
=> Don't require `cice_in.nml` namelist in CICE5 restarts

payu/models/cesm_cmeps.py, test/models/access-om3/test_access_om3.py, test/models/access-om3/test_runconfig.py, test/models/test_cesm_cmeps.py
This PR implements checks of the processors selected in the nuopc.runconfig file for the access-om3 payu driver.  This ensures that the processors requested for normal model operations and parallel IO are within range of the CPUs set in config.yaml and each model "realm" uses processors for IO that are within the range of processors for that realm.
It adds tests for the min/max bounds of each parameter.
Contributes to https://github.com/COSIMA/access-om3/issues/109
=> add checks of io layout to cmeps driver

docs/source/usage.rst, payu/branch.py, payu/subcommands/args.py, payu/subcommands/clone_cmd.py, test/test_branch.py
Added `--start-point/-s` argument to `payu clone` to specify what commit/tag/branch name to start new branches from. 
So there is still `-B/--branch` flag which initially checks out a branch during the `git clone` command. This was initially done (I think?) to avoid checking out a default branch first. For example, the [access-om2-configs repository](https://github.com/ACCESS-NRI/access-om2-configs/), the `main` branch is not a payu configuration.
The start point is used similarly to the `payu checkout`'s  positional argument, so 
```
payu clone -b ${NEW_BRANCH_NAME} -s ${COMMIT_OR_TAG} ${REPOSITORY} ${DIR}
```
is equivalent to running 
```
payu clone ${REPOSITORY} ${DIR}
payu checkout -b ${NEW_BRANCH_NAME} ${COMMIT_OR_TAG}
```
Closes #503
=> Add support for cloning configuration using a commit hash

payu/branch.py, test/test_branch.py
Added a fix for `payu clone -r` to resolve relative restart paths - with respect to the directory where `payu clone` is run from. I've changed it to call the helper method that checks restart path exists and resolves to an absolute path, before changing directory to the cloned repository which runs the `checkout` step. 
Closes #514
=> Fix clone with relative restart paths

docs/source/config.rst, payu/models/model.py, payu/models/test.py, test/test_pbs.py, test/test_setup.py
This PR:
- adds a step to model setup to resolve the input directory paths to absolute paths and resolve symlinks.
-  pass `follow_symlink=True` to copy commands when copying config files. However this is already a default value but I added in so it clear in the code that it's intentional.
- more tests for the above
In 0daf9115b65468e05f1db4bd8285fdc9a896c923, I had just one test that would run `payu setup` once and test that inputs, configuration files and executables that were set up as expected. In 6d975159f4102ac184ab13544f1dbbb451e2225e, I split up the tests to try(?) make it simpler to read and have one test for one thing. My concern was that it would make running tests slower as were running a `payu setup` multiple times. It ended up only adding a couple seconds to the tests..
To …
=> Support symbolic links in input files

docs/source/config.rst
Updated documentation that model executables can be specified by filenames, if found in paths loaded by model environment modules.
Closes #517
=> Update docs on model executable loaded via environment modules

payu/branch.py, payu/experiment.py, payu/laboratory.py, test/test_branch.py
This PR:
- In payu checkout - initialise laboratory directories before generating any metadata. This will fail with PermissionError if directories are non-writable, and prints some information on how to recover
- Fix a small error with changing archive symlinks when a previous directory has been deleted - added test
- Fix a uncaught warning when running payu checkout pytests
I was running with the idea of checking out a git branch - running checks on that branch and then if they failed, reverting the checkout back to the previous branch (and delete any new branches that were created). Though I then finally realised that it would make it difficult for the user to apply fixes on the branch/tag/commit they were starting from, e.g. fix project/shortpath/laboratory in config.yaml. It would …
=> Add error handling for payu checkout with non-writable laboratory

payu/models/yatm.py, test/models/test_yatm.py
Implements solution described here: https://github.com/payu-org/payu/issues/523#issuecomment-2398858187, which was to add an override the parent class `get_prior_restart_files` in `yatm`, to return just an empty array. This is to prevent error messaging on a missing prior restart directory when `yatm` driver does not require any.
Closes #523
=> Override yatm model class method for prior restarts

payu/models/access.py, payu/models/cice.py
Closes #534 
For CICE4 with AUSCOM set, restart pointer file contains:
`./iced.xxxx`
for CICE5, restart pointer file contains
`./RESTART/iced.xxxx`
=> fix cice5 restart pointers

docs/source/config.rst, payu/experiment.py, payu/fsops.py, payu/models/cice.py, payu/models/cice5.py, test/models/test_cice.py, test/test_payu.py
This draft PR addresses #527.
It adds a `compress_log_files` method, initially just to the `cice.py` driver. This  is called during the `archive` step and compresses all the log files matching some specified regex patterns into a tarball. A `compress_logs` option in the `config.yaml` file controls whether to run the compression.
I've marked this PR as a draft, as I'd be keen to see if the implementation looks reasonable to others, and if so I think it would be good to move the changes over to the general `model` class making it available to each model.
=> Model log compression

payu/models/cice.py, test/models/test_cice.py
This PR closes #541.
Regex patterns for finding log files previously broke when no log files were specified, as done for CICE5. Instead of matching no files, the `get_log_files()` method would match every file in the model work directory.
This PR adds checks at the start of the `get_log_files()` and `compress_log_files()` methods, causing them to exit early when no log files are specified, and when no log files are found.
It also adds a unit test `test_log_compression_no_logs()` to `test_cice.py` which makes sure that the compression method does nothing when no log files are specified.
With these changes, OM2 runs without any issues.
=> Fix log compression bug when no logs specified

payu/cli.py, payu/experiment.py, payu/schedulers/__init__.py, payu/schedulers/pbs.py, payu/schedulers/scheduler.py
Closes #545 
This fixes the PBS scheduler `get_qstat_info()` method which was always failing due to `PBS_EXEC` no longer being defined in the environment. Because it is wrapped in a  `tenancity` retry, it would retry the command for 10s. I've changed  to call `qstat` command directly as this seems available on the `$PATH` in PBS jobs. This now results in PBS specific job information being added to the `job.yaml` in the output archive directory.
I've also done a small change to move `get_job_info()` and `get_job_id()` to scheduler class methods - that are extended in the PBS scheduler subclass. This to avoid importing `scheduler.pbs` in `experiment.py`.
Tested that the `job.yaml` populated with PBS run info when running a small [MOM6 …
=> Fix job.yaml qstat call

docs/source/config.rst
=> Clarify jobfs docs

payu/models/cesm_cmeps.py
Closes #555 
This lets the user set the restart time as they desire!
=> Remove setting restart time in access-om3 driver

docs/source/config.rst, payu/models/cesm_cmeps.py, test/models/access-om3/test_access_om3.py
Closes #506 
This adds support for date based restart pruning to the access-om3 driver.
This uses the payu framework for restart pruning, the only addition is a `get_restart_datetime()`
function with the a access-om3 class.
=> Add restart pruning to OM3 driver

payu/models/__init__.py, payu/models/access_esm1p6.py
Closes the first part of #554
This PR adds an initial driver for ESM 1.6. This first version duplicates the ESM1.5 driver which until now has been used for ESM1.6. ESM1.6 specific changes (e.g. adding new configuration files, removing `matm` support) will be added in separate PRs in order to have clearer diffs. 
The most contentious part could be the file and model names – I tried to follow what I'd seen elsewhere but let me know if there are different conventions that would be better.
- I chose the filename `access_esm1p6.py` based on `accessom2.py`, however added an underscore for clarity since they are used in other drivers like `cesm_cmeps.py` include them.
- For naming the model class, I used `AccessEsm1p6`, following other classes like `AccessOm2`.
- For the `model-type` I used …
=> Add initial driver for ACCESS-ESM1.6

payu/models/access_esm1p6.py, payu/models/um.py, test/models/test_access_esm1p6.py
Closes #569 
This PR adds two optional configuration files, `soil.nml` and `pft_params.nml` to the UM via the `access-esm1.6` driver. 
I'll add some comments elaborating on the implementation, but any feedback and suggested changes are welcome!
=> Add new cable 3 namelists to ESM1.6 driver

payu/git_utils.py, payu/models/cesm_cmeps.py, payu/models/mom6.py, test/common.py, test/models/access-om3/test_access_om3.py, test/models/test_mom6.py, test/test_git_utils.py, test/test_setup.py
Closes #565 
When using the access-om3 driver, the commits the MOM output documentation (`MOM_parameter_doc.*`) into the `docs` folder of the config being run.
If `runlog: False` it adds the docs folder it without committing
If `runlog: True` it commits it, with the message "payu archive: documentation of MOM6 run-time configuration" 
@dougiesquire - do you have a MOM6 standalone config i can test this with ?
@chrisb13 - if you'd like, we could try and do an "online/in zoom" review for training purposes. We probably need @jo-basevi because i'm a hack
=> Commit MOM_parameter_doc.* into docs folder of config

payu/branch.py, payu/subcommands/checkout_cmd.py, payu/subcommands/clone_cmd.py, test/test_branch.py
Add a check to `payu clone` for when `-s/--start-point` to start from a commit/tag is defined but a new branch name with `-b` is not set. Closes #574  
The now error becomes: 
```
$ payu clone -s dev-MC_025deg_jra_ryf-0.4 https://github.com/access-nri/access-om3-configs my_folder
Traceback (most recent call last):
File "/scratch/project/user/payu-telemetry-venv/bin/payu", line 8, in <module>
sys.exit(parse())
^^^^^^^
File "/home/189/user/payu_fork/payu/cli.py", line 49, in parse
run_cmd(**args)
File "/home/189/user/payu_fork/payu/subcommands/clone_cmd.py", line 37, in runcmd
clone(repository=repository,
File "/home/189/user/payu_fork/payu/branch.py", line 297, in clone
raise PayuBranchError(
payu.git_utils.PayuBranchError: Starting from a specific commit or tag requires a new branch name …
```
=> Add error messaging when cloning from tag/commit

docs/source/config.rst
Add a brief description of  `exe_prefix` to the Model configuration section.
Closes #578
=> Add exe_prefix option to documentation

payu/experiment.py
Switched the order of collation submission and running the archive userscript to ensure the archive user script completes before collation starts.
Closes #583
=> Move running archive userscript to before collation job is submitted

docs/source/config.rst, payu/models/access.py, payu/models/access_esm1p6.py, payu/models/cesm_cmeps.py, payu/models/mitgcm.py, payu/models/mom6.py, payu/models/um.py
Contributes to #576 
This enables the repeat option to be used with previous restart files to start (rather than always assuming they are starting from an initial condition).
Ad-hoc testing only. This works with the access-esm1.6 driver now. I've assumed that users specify the restart in `config.yaml` and do not already have restart's in their archive directory.
=> allow repeat_run from a restart defined in config.yaml

payu/models/access_esm1p6.py
Closes #595. 
Updates the `access-esm1.6` driver so that start date information is written to the CICE `input_ice.nml` namelist only for CICE4, and not CICE5. ~Should be merged around the same time as https://github.com/ACCESS-NRI/cice5/pull/48 to maintain compatibility.~ actually timing doesn't matter too much, as long as we add this in when swapping to an updated cice5 build
=> Don't write start date to CICE5 namelist

payu/experiment.py, test/test_setup.py
This PR checks if there are any pre-existing restarts in archive when setting `prior_restart_path` to allow the case of a non-zero counter (i.e. run number which is used for output naming) and using a user defined restart directory in `config.yaml`. (This means for continuing a run from a new empty archive, it is possible to set `restart: path/to/last/restart9` in `config.yaml` and start new run using `payu run -i 10` which result in output directories `output010` and `restart011` )
I've also changed an assert, and printed warning to exceptions. I'm still raising a warning when using a restart from `config.yaml` with a non-zero counter so there's some visibility on what payu is doing. 
I'm still trying to think of a case where using a restart in `config.yaml` and a non-zero counter would …
=> Allow starting from user-restart when empty archive and non-zero counter

payu/models/um.py, test/models/test_um.py
Closes #609.
Consistently read and write the `um_res.yaml` file using `datetime.datetime` objects. This maintains compatibility with the files that the driver writes, and maintains compatibility with other date manipulations within the UM driver which expect datetime.datetime objects (e.g. [here](https://github.com/payu-org/payu/blob/3f79a0d0a57f1e9bb86b20fe2a11ef4f5991a5a1/payu/models/um.py#L192-L198)). Convert to `cftime.datetime` after reading.
=> Revert um calendar format change

payu/schedulers/pbs.py, test/test_pbs.py
Related to https://github.com/ACCESS-NRI/model-release-condaenv/issues/17 which requires running payu from an environment within a singularity container. 
This allows a custom launcher script to run at the start of the PBS job which launches a singularity container with a SquashFS overlay for the environment, and then runs the python and payu executable within that environment.
Could use a shorter or other name than `ENV_LAUNCHER_SCRIPT_PATH`? Now would be the time to change it if so..
I've manually tested that this does not add `ENV_LAUNCHER_SCRIPT_PATH` if it isn't set in the environment, and if it is, it then works with an launcher script implementation in the https://github.com/ACCESS-NRI/model-release-condaenv/pull/19 PR. 
Note: qsub call looks like `qsub <qsub_flags> -- …
=> Prepend container launcher script to pbs command, if it exists

payu/experiment.py, payu/models/fms.py
Move listing loaded modules until after openmpi has been potentially been updated. This should make it more clear what modules are loaded by the time the model runs
Closes #605
=> List loaded modules after openmpi has been updated

pyproject.toml
`netCDF4` is imported in CICE5 model driver, but was previously available in the environment due to an older version of `yamanifest` dependency. This PR adds `netCDF4` explicitly to the project dependencies.
Closes #613
=> Add netCDF4 as a explicit dependency

.github/workflows/CD.yml, .github/workflows/CI.yml
This PR updates the [`pypa/gh-action-pypi-publish`](https://github.com/pypa/gh-action-pypi-publish) action used in the CD workflow to `v1.12.4` so it can support newer versions of `twine`.
Closes #615
=> Update pypa/gh-action-pypi-publish to v1.12.4

payu/models/cice.py, test/models/test_cice5.py
Closes #617 
- Allow for `history_dir` to not be set and use a default value
- Error if `restar_dir` is not set, as payu relies on it for tracking restarting files.
=> Tidy up handling history_dir and restart_dir

payu/models/cesm_cmeps.py
closes https://github.com/payu-org/payu/issues/620
This PR patches collate method in CesmCmeps to automatically locate `nuopc.runconfig` when the user collates a bare restart directory with `payu collate -d archive/restartxxx` or `payu collate -d restartxxx`,
1. lookinig for sibling `outputxxx` directory obtained by `restartxxx -> outputxxx`
2. If absent, fall back to the copy in `control/`.
=> Autodetect nuopc.runconfig for restart-only collate

payu/models/roms.py
Enabled `optional_config_files` provision through `config.yaml`. Prior to this change, ROMS `varinfo` file was being considered a mandatory model config file and mistakenly hard coded into `config_files` list, leading to model initialisation failure when file name differed from `varinfo_seacofs.yaml`.
=> fix: properly handle provision of optional configuration files
